CS_Detect_Alerts:
  alerting: true
  archive_time: null
  archived: false
  create_time: '2024-10-19T08:29:45.240959Z'
  enabled: true
  id: ru_73dfc757-b98a-43c2-a495-cffdba97d00d
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_73dfc757-b98a-43c2-a495-cffdba97d00d
  revision_create_time: '2024-10-19T08:31:38.780303Z'
  revision_id: v_1729326698_780303000
  run_frequency: LIVE
  type: SINGLE_EVENT
Fin7_Dridex_TTP:
  alerting: false
  archive_time: null
  archived: false
  create_time: '2025-02-04T10:35:36.528639Z'
  enabled: false
  id: ru_98b3d1aa-866a-47b1-be83-346282a21329
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_98b3d1aa-866a-47b1-be83-346282a21329
  revision_create_time: '2025-02-04T10:35:36.528639Z'
  revision_id: v_1738665336_528639000
  run_frequency: LIVE
  type: MULTI_EVENT
GCP_gcp_admin_privileged_roles_added_to_service_accounts:
  alerting: false
  archive_time: null
  archived: false
  create_time: '2025-02-26T06:55:07.146319Z'
  enabled: false
  id: ru_406a164f-d1f7-42cc-b845-f3846537b03b
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_406a164f-d1f7-42cc-b845-f3846537b03b
  revision_create_time: '2025-02-26T06:55:07.146319Z'
  revision_id: v_1740552907_146319000
  run_frequency: LIVE
  type: SINGLE_EVENT
demoday_akira:
  alerting: false
  archive_time: null
  archived: false
  create_time: '2025-03-03T19:13:04.121679Z'
  enabled: false
  id: ru_dee4a64d-9d58-436f-a05e-d5ef326267a0
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_dee4a64d-9d58-436f-a05e-d5ef326267a0
  revision_create_time: '2025-04-22T03:48:20.103647Z'
  revision_id: v_1745293700_103647000
  run_frequency: LIVE
  type: MULTI_EVENT
demoday_akira_ransomextension:
  alerting: false
  archive_time: null
  archived: false
  create_time: '2025-05-15T06:42:35.674591Z'
  enabled: false
  id: ru_6a2a9421-5616-49db-851c-7fa408b82fd2
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_6a2a9421-5616-49db-851c-7fa408b82fd2
  revision_create_time: '2025-05-15T06:43:19.882015Z'
  revision_id: v_1747291399_882015000
  run_frequency: LIVE
  type: MULTI_EVENT
demoday_akira_ttp_t1546_003:
  alerting: false
  archive_time: null
  archived: false
  create_time: '2025-02-24T06:30:03.969519Z'
  enabled: true
  id: ru_dd40954f-9112-44d9-bab9-6ec3396b2f9a
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_dd40954f-9112-44d9-bab9-6ec3396b2f9a
  revision_create_time: '2025-02-24T07:12:00.778239Z'
  revision_id: v_1740381120_778239000
  run_frequency: LIVE
  type: SINGLE_EVENT
demoverse_Chrome_Browser_Alert_SideLoaded_Extensions:
  alerting: true
  archive_time: null
  archived: false
  create_time: '2025-02-26T08:13:18.344047Z'
  enabled: true
  id: ru_f232e4e7-e5ad-4530-92fe-97e4c07f2ad6
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_f232e4e7-e5ad-4530-92fe-97e4c07f2ad6
  revision_create_time: '2025-02-26T08:13:18.344047Z'
  revision_id: v_1740557598_344047000
  run_frequency: LIVE
  type: SINGLE_EVENT
encoded_powershell:
  alerting: true
  archive_time: null
  archived: false
  create_time: '2024-10-18T07:15:57.499503Z'
  enabled: true
  id: ru_3168e7d6-4caf-428f-b0c7-522a8da39f49
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_3168e7d6-4caf-428f-b0c7-522a8da39f49
  revision_create_time: '2025-01-30T04:50:32.731631Z'
  revision_id: v_1738212632_731631000
  run_frequency: LIVE
  type: SINGLE_EVENT
rule_1729234935917:
  alerting: false
  archive_time: '2024-10-18T07:17:48.405460Z'
  archived: true
  create_time: '2024-10-18T07:02:40.963487Z'
  enabled: false
  id: ru_a1e9ba71-4e03-4292-9827-69a19562add8
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_a1e9ba71-4e03-4292-9827-69a19562add8
  revision_create_time: '2024-10-18T07:02:40.963487Z'
  revision_id: v_1729234960_963487000
  run_frequency: LIVE
  type: SINGLE_EVENT
suspicious_command_net_user:
  alerting: true
  archive_time: null
  archived: false
  create_time: '2024-10-18T07:19:47.831935Z'
  enabled: true
  id: ru_2c0a3514-a3b0-46e7-a3ed-fcdc0782e6f4
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_2c0a3514-a3b0-46e7-a3ed-fcdc0782e6f4
  revision_create_time: '2024-10-18T07:19:47.831935Z'
  revision_id: v_1729235987_831935000
  run_frequency: LIVE
  type: SINGLE_EVENT
test_regsvr32_AllTheThingsx86_atomicredtest:
  alerting: true
  archive_time: null
  archived: false
  create_time: '2025-02-06T02:58:01.423295Z'
  enabled: true
  id: ru_8cfd3b4e-bbc9-485b-90d3-9677889091cb
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_8cfd3b4e-bbc9-485b-90d3-9677889091cb
  revision_create_time: '2025-02-24T06:53:54.136495Z'
  revision_id: v_1740380034_136495000
  run_frequency: LIVE
  type: SINGLE_EVENT
vt_malicious_file_verdict:
  alerting: false
  archive_time: null
  archived: false
  create_time: '2025-05-22T06:52:30.838079Z'
  enabled: false
  id: ru_7715e363-4527-4881-acc3-57cca1a2a421
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_7715e363-4527-4881-acc3-57cca1a2a421
  revision_create_time: '2025-05-22T06:56:40.139599Z'
  revision_id: v_1747897000_139599000
  run_frequency: LIVE
  type: SINGLE_EVENT
win_defender_alerts:
  alerting: true
  archive_time: null
  archived: false
  create_time: '2024-11-12T15:33:17.796943Z'
  enabled: true
  id: ru_d952f7ce-b70c-4395-8bc7-318b6dc9ea3a
  resource_name: projects/651850292640/locations/us/instances/84cfb81b-b702-4249-a6d0-3167312684b5/rules/ru_d952f7ce-b70c-4395-8bc7-318b6dc9ea3a
  revision_create_time: '2024-11-12T16:07:08.334575Z'
  revision_id: v_1731427628_334575000
  run_frequency: LIVE
  type: SINGLE_EVENT
